###Listado de reservas por paciente
###
GET http://localhost:8081/pacientes/reservas/903


###Paciente cancela consulta
DELETE http://localhost:8081/pacientes/consulta/cancelada/121

###Registrar consulta
POST http://localhost:8081/pacientes/reservas
Content-Type: application/json

{
    "id_consultas":null,
    "id_paciente":1,
    "fecha":"2022-09-26",
    "id_horario":2,
    "id_estado_consulta":1,
    "id_consultorio":1,
    "id_atencion":1,
    "informe_consulta":""
}
###Listado de las especialidades existentes
GET http://localhost:8081/medicos/especialidades

###Listado de medicos por especialidades
GET http://localhost:8081/medicos/especialidades/1


###Obtener id de atencion por id de medico y su especialidad
GET http://localhost:8081/medicos/atencion?id_medico=8&id_especialidades=2


###Obtener estados de consultas
GET http://localhost:8081/medicos/estados-consultas

###Otener recetas de consulta
GET http://localhost:8081/medicos/consulta/receta/117

###Eliminar receeta de consulta
DELETE http://localhost:8081/medicos/consulta/receta/15

###Actualizar detalle de consulta
PUT http://localhost:8081/medicos/consulta/detalle/1
Content-Type: application/json

{
    "id_estado_consulta":1,
    "informe_consulta":"detalles"
}
###Regsitrar nueva receta
POST http://localhost:8081/medicos/consulta/receta
Content-Type: application/json

{
    "descripcion": "Descripcion dolor de garganta",
    "habilitado_recogo": 1,
    "id_consultas": "117",
    "id_receta": null,
    "titulo": "Receta para dolor de garganta"
}

###Actualizar datos de consulta
PUT http://localhost:8081/pacientes/reservas/123
Content-Type: application/json

{
    "id_paciente":3,
    "fecha":"2022-09-26",
    "id_horario":2,
    "id_estado_consulta":1,
    "id_consultorio":1,
    "id_atencion":1,
    "informe_consulta":""
}

### Multiples parametros
GET http://localhost:8081/medicos/consultas-dia?id_medico=3&fecha=2022-09-25


###Obtener estados de consulta


### Buscar horarios disponibles por atencion y fecha
GET http://localhost:8081/pacientes/consultas-disponibles?id_atencion=5&fecha=2022-09-28

###HOJAS TRASPASO------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###Registrar hojas traspaso
POST http://localhost:8081/medicos/hojas-traspaso
Content-Type: application/json

{
    "id_hoja_traspaso":null,
    "id_consultas":1,
    "examen_clinico":"Examen clinico registrando...",
    "diagnostico_presuntivo":"Diagnostico presuntivo registrando..."
}
###Obtener hojas de traspaso de consulta
GET http://localhost:8081/medicos/consulta/hojas-traspaso/1

###Eliminar hoja de traspaso 
DELETE  http://localhost:8081/medicos/hojas-traspaso/5

###ORDENES DE LABORATORIO------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###Registrar orden laboratorio
POST http://localhost:8081/medicos/orden-laboratorio
Content-Type: application/json

{
    "id_orden_laboratorio":null,
    "id_consultas":1,
    "descripcion":"Nueva orden laboratorio 2..."
}
###Obtener todas ordenes de laboratorio
GET http://localhost:8081/medicos/orden-laboratorio

###Obtener ordenes de laboratorio de acuerdo a la consulta
GET http://localhost:8081/medicos/consulta/orden-laboratorio/1
###Eliminar orden de laboratorio
DELETE http://localhost:8081/medicos/orden-laboratorio/3


###ADM
###ADM
###ADM
###ADM
###ADM
###ADM
###ADM

GET http://localhost:8081/adm/pacientes

###Obtener id de atencion por id de medico y su especialidad
GET http://localhost:8081/adm/consultas-dia?fecha=2022-10-11

###Eliminar consulta adm
DELETE http://localhost:8081/adm/consulta/1
