###Listado de reservas por paciente
GET http://localhost:8081/pacientes/reservas/903


###Paciente cancela consulta
DELETE http://localhost:8081/pacientes/consulta/cancelada/17

###Registrar consulta
POST http://localhost:8081/pacientes/reservas
Content-Type: application/json

{
    "id_consultas":null,
    "id_paciente":1,
    "fecha":"2022-09-26",
    "id_horario":2,
    "id_estado_consulta":1,
    "id_consultorio":1,
    "id_atencion":1
}
###Listado de las especialidades existentes
GET http://localhost:8081/medicos/especialidades

###Listado de medicos por especialidades
GET http://localhost:8081/medicos/especialidades/1


###Obtener atencion de medico y su especialidad
GET http://localhost:8081/medicos/atencion?id_medico=8&id_especialidades=3


###Actualizar datos de consulta
PUT http://localhost:8081/pacientes/reservas/101
Content-Type: application/json

{
    "id_paciente":3,
    "fecha":"2022-09-26",
    "id_horario":2,
    "id_estado_consulta":1,
    "id_consultorio":1,
    "id_atencion":1
}

### Multiples parametros
GET http://localhost:8081/pacientes/consultas-dia?id_medico=3&fecha=2022-09-25


### Buscar horarios disponibles por atencion y fecha
GET http://localhost:8081/pacientes/consultas-disponibles?id_atencion=5&fecha=2022-09-28
