###Listado de reservas por paciente
GET http://localhost:8081/pacientes/reservas/903


###Paciente cancela consulta
DELETE http://localhost:8081/pacientes/consulta/cancelada/17

###Registrar consulta
POST http://localhost:8081/pacientes/reservas
Content-Type: application/json

{
    "id_consultas":null,
    "id_paciente":1,
    "fecha":"2022-09-26",
    "id_horario":2,
    "id_estado_consulta":1,
    "id_consultorio":1,
    "id_atencion":1
}
###Listado de las especialidades existentes
GET http://localhost:8081/medicos/especialidades

###Listado de medicos por especialidades
GET http://localhost:8081/medicos/especialidades/1


###Obtener id de atencion por id de medico y su especialidad
GET http://localhost:8081/medicos/atencion?id_medico=8&id_especialidades=2


###Obtener estados de consultas
GET http://localhost:8081/medicos/estados-consultas

###Otener recetas de consulta
GET http://localhost:8081/medicos/consulta/receta/117

###Regsitrar nueva receta
POST http://localhost:8081/medicos/consulta/receta
Content-Type: application/json

{
    "descripcion": "Descripcion dolor de garganta",
    "habilitado_recogo": 1,
    "id_consultas": "117",
    "id_receta": null,
    "titulo": "Receta para dolor de garganta"
}

###Actualizar datos de consulta
PUT http://localhost:8081/pacientes/reservas/101
Content-Type: application/json

{
    "id_paciente":3,
    "fecha":"2022-09-26",
    "id_horario":2,
    "id_estado_consulta":1,
    "id_consultorio":1,
    "id_atencion":1
}

### Multiples parametros
GET http://localhost:8081/medicos/consultas-dia?id_medico=3&fecha=2022-09-25


###Obtener estados de consulta


### Buscar horarios disponibles por atencion y fecha
GET http://localhost:8081/pacientes/consultas-disponibles?id_atencion=5&fecha=2022-09-28
